import { Matter } from '@/types';

export const INITIAL_MATTERS: Matter[] = [
  {
    id: 'm1',
    title: 'Sharma v. State of Maharashtra',
    court: 'Bombay High Court',
    caseNo: 'MAT-2026-0148',
    area: 'Criminal · Anticipatory Bail',
    stage: 2,
    lead: 'Shreyas A.',
    leadInitials: 'SA',
    updated: '15 min ago',
    nextHearing: {
      date: '11 Sep 2026',
      dateISO: '2026-09-11',
      time: '10:30 AM',
      purpose: 'Anticipatory bail hearing',
      court2: 'Courtroom 52',
    },
    tags: ['Economic offence', 'Bail', 'High priority'],
    facts: {
      objective: 'Secure interim protection for the applicant and place the documented cooperation record before the court.',
      relief: 'Anticipatory bail under Section 482, Bharatiya Nagarik Suraksha Sanhita, 2023 (formerly Section 438, CrPC).',
      issue: 'Whether custodial interrogation is necessary given the applicant’s complete cooperation and the commercial nature of the alleged offence.',
    },
    authorities: [
      { key: 'sushila', title: 'Sushila Aggarwal v. State (NCT of Delhi)', meta: '2020 · 5 SCC 1 · Supreme Court', pinned: true },
      { key: 'siddharam', title: 'Siddharam Satlingappa Mhetre v. State of Maharashtra', meta: '2011 · 1 SCC 694 · Supreme Court', pinned: true },
      { key: 's482', title: 'Section 482, Bharatiya Nagarik Suraksha Sanhita, 2023', meta: 'Statute · Bare Act', pinned: true },
    ],
    arguments: [
      {
        point: 'The applicant has cooperated at every stage of the investigation.',
        support: 'Supported by the cooperation email chain and two recorded statements before the investigating officer.',
        strength: 84,
        stressTest: 'Opposing precedent: documented cooperation does not by itself rule out custody if fresh material emerges. Keep affidavit strictly specific to voluntary submissions.',
      },
      {
        point: 'The alleged offence is commercial in nature, with no risk of violence or tampering.',
        support: 'FIR discloses a financial contract dispute; no allegation of threat or tampering.',
        strength: 76,
        stressTest: 'The State could argue economic offences are a class apart. Brief should highlight the civil/contractual nexus.',
      },
      {
        point: 'Custodial interrogation serves no investigative purpose here.',
        support: 'All documents the State seeks have already been voluntarily produced.',
        strength: 65,
        stressTest: 'No opposing precedent directly on point in the indexed corpus.',
      },
    ],
    counterArgs: [
      {
        point: 'The State may emphasise the quantum of the alleged financial loss.',
        rebuttal: 'Quantum of loss does not by itself establish need for custody — liberty is default absent custodial requirement.',
      },
      {
        point: 'The complainant may allege a flight risk.',
        rebuttal: 'Applicant has fixed residence in Mumbai, valid passport with no overseas travel, and offers to deposit passport.',
      },
    ],
    tasks: [
      { label: 'Confirm investigating officer’s notice date', done: true },
      { label: 'Attach cooperation email chain as Annexure C', done: false },
      { label: 'Verify applicant’s current address on affidavit', done: true },
    ],
    evidenceDocs: [
      {
        id: 'doc-1',
        title: 'First Information Report (FIR No. 211/2026)',
        type: 'Police Record',
        date: '14 Feb 2026',
        dateISO: '2026-02-14',
        summary: 'Allegations under Section 420/406 IPC filed at Andheri Police Station mentioning ₹50,00,000.',
        pages: 4,
        annexure: 'A',
        text: 'FIR No. 211/2026 registered at Andheri Police Station on 14 February 2026. The complainant alleges payment of Rs. 50,00,000 towards commercial supply. Notice issued under Section 41A on 20 February 2026.',
        status: 'indexed',
      },
      {
        id: 'doc-2',
        title: 'Memorandum of Understanding / Commercial Agreement',
        type: 'Agreement',
        date: '12 Jan 2025',
        dateISO: '2025-01-12',
        summary: 'Underlying contract specifying payment tranches and delivery terms.',
        pages: 12,
        annexure: 'B',
        text: 'Agreement executed on 12 January 2025. Total consideration agreed was Rs. 50,00,000 payable across three tranches. Dispute resolution via arbitration in Mumbai.',
        status: 'indexed',
      },
      {
        id: 'doc-3',
        title: 'Investigating Officer Notice under Section 41A',
        type: 'Notice',
        date: '20 Feb 2026',
        dateISO: '2026-02-20',
        summary: 'Notice directing attendance before IO on 24 Feb 2026.',
        pages: 2,
        annexure: 'C',
        text: 'Notice under Section 41A CrPC dated 20 February 2026 requiring applicant presence on 24 February 2026. Attended and cooperation letter submitted.',
        status: 'indexed',
      },
    ],
    chronology: [
      { date: '12 Jan 2025', dateISO: '2025-01-12', event: 'Commercial MoU executed between parties', sourceDoc: 'Agreement', badge: 'Contract' },
      { date: '14 Feb 2026', dateISO: '2026-02-14', event: 'FIR No. 211/2026 registered at Andheri PS', sourceDoc: 'FIR No. 211/2026', badge: 'Police' },
      { date: '20 Feb 2026', dateISO: '2026-02-20', event: 'Section 41A notice served upon applicant', sourceDoc: 'Notice under S.41A', badge: 'Process' },
      { date: '24 Feb 2026', dateISO: '2026-02-24', event: 'Applicant attended IO and recorded voluntary statement', sourceDoc: 'IO Statement', badge: 'Cooperation' },
      { date: '11 Sep 2026', dateISO: '2026-09-11', event: 'Anticipatory bail hearing before Bombay HC', sourceDoc: 'Cause List', badge: 'Hearing' },
    ],
    notes: [
      {
        id: 'n1',
        title: 'Strategy for Senior Counsel Brief',
        date: '08 Sep 2026',
        body: 'Emphasize that the dispute is fundamentally an accounting dispute under the 2025 contract. Cite Siddharam Mhetre para 112 on liberty.',
      },
    ],
  },
  {
    id: 'm2',
    title: 'Aarohi Estates Pvt. Ltd. v. Suresh Patel',
    court: 'City Civil Court, Mumbai',
    caseNo: 'CS-2026-4521',
    area: 'Civil · Commercial Suit',
    stage: 1,
    lead: 'Rohan M.',
    leadInitials: 'RM',
    updated: '1 hour ago',
    nextHearing: {
      date: '18 Sep 2026',
      dateISO: '2026-09-18',
      time: '11:00 AM',
      purpose: 'Hearing on Interim Injunction',
      court2: 'Courtroom 14',
    },
    tags: ['Commercial', 'Specific Performance', 'Injunction'],
    facts: {
      objective: 'Obtain temporary injunction restraining alienation of Plot 12 and enforce development rights.',
      relief: 'Injunction under Order XXXIX Rules 1 & 2 CPC.',
      issue: 'Whether time was of the essence in the development agreement.',
    },
    authorities: [
      { key: 'art54', title: 'Article 54, Limitation Act, 1963', meta: '3 Years from date of refusal', pinned: true },
      { key: 'o8r1', title: 'Order VIII Rule 1, CPC', meta: 'Written statement time limits', pinned: true },
    ],
    arguments: [
      {
        point: 'Plaintiff paid substantial consideration of ₹5 Crore upfront.',
        support: 'Bank RTGS receipts annexed to plaint.',
        strength: 90,
      },
      {
        point: 'Defendant failed to deliver clear handover by agreed deadline.',
        support: 'Notice dated 2 December 2025 remaining uncomplied.',
        strength: 82,
      },
    ],
    counterArgs: [
      {
        point: 'Defendant claims oral extension was granted.',
        rebuttal: 'Clause 18 requires all amendments to be in writing signed by both parties.',
      },
    ],
    tasks: [
      { label: 'Draft reply to Defendant’s interim application', done: false },
      { label: 'Calculate commercial limitation for written statement', done: true },
    ],
    evidenceDocs: [
      {
        id: 'doc-m2-1',
        title: 'Development Agreement',
        type: 'Contract',
        date: '12 Jun 2025',
        dateISO: '2025-06-12',
        summary: 'Agreement regarding Plot 12 development for consideration of Rs. 5 crore.',
        pages: 18,
        annexure: 'A',
        text: 'Development agreement executed 12 June 2025. Consideration of Rs. 5 crore payable in three tranches. Handover was due on 30 November 2025.',
        status: 'indexed',
      },
      {
        id: 'doc-m2-2',
        title: 'Legal Notice of Handover Default',
        type: 'Notice',
        date: '02 Dec 2025',
        dateISO: '2025-12-02',
        summary: 'Demand notice giving 15 days to deliver vacant possession.',
        pages: 3,
        annexure: 'B',
        text: 'Notice issued on 2 December 2025 calling upon Defendant to handover peaceful vacant possession of Plot 12 within 15 days.',
        status: 'indexed',
      },
    ],
    chronology: [
      { date: '12 Jun 2025', dateISO: '2025-06-12', event: 'Development agreement signed', sourceDoc: 'Development Agreement' },
      { date: '30 Nov 2025', dateISO: '2025-11-30', event: 'Handover deadline elapsed', sourceDoc: 'Contract Clause 4' },
      { date: '02 Dec 2025', dateISO: '2025-12-02', event: 'Notice of default issued', sourceDoc: 'Notice' },
      { date: '18 Sep 2026', dateISO: '2026-09-18', event: 'Injunction hearing in City Civil Court', sourceDoc: 'Court Board' },
    ],
  },
];
